### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by rajasekharan** [wit-ai/pywit#34]
Hello,
I am using pywit for my project. I have followed the documentation provided on ( wit.ai ). As mentioned in the documentation, i created a story, downloaded pywit and installed as show in( https://github.com/wit-ai/pywit ). when i tried to run the example program, I am facing the below issues:

rajasekharan@ubuntu:~/pywit-master$ sudo python examples/quickstart.py <gave my client access token> 
> what's the weather?
Traceback (most recent call last):
  File "examples/quickstart.py", line 44, in <module>
    client.interactive()
  File "/usr/local/lib/python2.7/dist-packages/wit/wit.py", line 141, in interactive
    context = self.run_actions(session_id, message, context, max_steps)
  File "/usr/local/lib/python2.7/dist-packages/wit/wit.py", line 115, in run_actions
    message)
  File "/usr/local/lib/python2.7/dist-packages/wit/wit.py", line 72, in __run_actions
    rst = self.converse(session_id, message, context)
  File "/usr/local/lib/python2.7/dist-packages/wit/wit.py", line 66, in converse
    return req(self.access_token, 'POST', '/converse', params, json=context)
  File "/usr/local/lib/python2.7/dist-packages/wit/wit.py", line 22, in req
    **kwargs
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'

Kindly help me in solving this issue.

**Comment by Utkagr** [comment]
I am having the same problem.

**Comment by Utkagr** [comment]
I tried updating each of these packages mentioned below and it worked.
Also,python 2.7 was throwing some other error. Python(>3) worked.

requests (2.9.1)
setuptools (20.9.0)
simplejson (3.8.2)
wheel (0.29.0)
wit (3.4.0)

**Comment by patapizza** [comment]
Yes this should have been fixed in v3.2 (see https://github.com/wit-ai/pywit/commit/35c4b2fa432b10cd43d15a4ec83c6f92e912847f).

**Comment by prahaladv** [comment]
I'm using the latest version, but still ending up with the same error. What could be the reason? Thanks! :)

**Comment by zen0x90** [comment]
same here :
  INSTALLED: 2.13.0 (latest)

**Comment by lordlabakdas** [comment]
I am running requests 2.13.0 and still getting the same error.
